version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '80:80'
    links:
      - db
    networks:
        vpcbr:
          ipv4_address: 192.167.3.3

  db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: 7a72*Wdv
            MYSQL_DATABASE: pruebas
            MYSQL_USER: user_pruebas
            MYSQL_PASSWORD: 7a72*Wdv

        networks:
             vpcbr:
                  ipv4_address: 192.167.3.4

        # Autostart at boottime
        # restart: always

networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
                - subnet: 192.167.3.0/16
                  gateway: 192.167.3.1
